### ISSUE TITLE
storage labs

### ISSUE THREAD

**Issue by erikabreo16** [erikabreo16/SEBC#2]

**Comment by erikabreo16** [comment]
--salida TERAGEN

[root@ip-172-31-38-4 hadoop-mapreduce]# sudo -u erikabreo16 time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar teragen -Dmapred.compress.map.output=false -Dmapreduce.jobs.maps=4 32000 /user/erikabreo16/teragen
17/07/19 22:59:26 INFO client.RMProxy: Connecting to ResourceManager at ip-172-31-43-140.us-west-2.compute.internal/172.31.43.140:8032
17/07/19 22:59:26 INFO terasort.TeraGen: Generating 32000 using 2
17/07/19 22:59:27 INFO mapreduce.JobSubmitter: number of splits:2
17/07/19 22:59:27 INFO Configuration.deprecation: mapred.compress.map.output is deprecated. Instead, use mapreduce.map.output.compress
17/07/19 22:59:27 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1500493697580_0003
17/07/19 22:59:27 INFO impl.YarnClientImpl: Submitted application application_1500493697580_0003
17/07/19 22:59:27 INFO mapreduce.Job: The url to track the job: http://ip-172-31-43-140.us-west-2.compute.internal:8088/proxy/application_1500493697580_0003/
17/07/19 22:59:27 INFO mapreduce.Job: Running job: job_1500493697580_0003
17/07/19 22:59:34 INFO mapreduce.Job: Job job_1500493697580_0003 running in uber mode : false
17/07/19 22:59:34 INFO mapreduce.Job:  map 0% reduce 0%
17/07/19 22:59:40 INFO mapreduce.Job:  map 100% reduce 0%
17/07/19 22:59:40 INFO mapreduce.Job: Job job_1500493697580_0003 completed successfully
17/07/19 22:59:40 INFO mapreduce.Job: Counters: 33
        File System Counters
                FILE: Number of bytes read=0
                FILE: Number of bytes written=255586
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
                HDFS: Number of bytes read=164
                HDFS: Number of bytes written=3200000
                HDFS: Number of read operations=8
                HDFS: Number of large read operations=0
                HDFS: Number of write operations=4
        Job Counters
                Launched map tasks=2
                Other local map tasks=2
                Total time spent by all maps in occupied slots (ms)=7295
                Total time spent by all reduces in occupied slots (ms)=0
                Total time spent by all map tasks (ms)=7295
                Total vcore-milliseconds taken by all map tasks=7295
                Total megabyte-milliseconds taken by all map tasks=7470080
        Map-Reduce Framework
                Map input records=32000
                Map output records=32000
                Input split bytes=164
                Spilled Records=0
                Failed Shuffles=0
                Merged Map outputs=0
                GC time elapsed (ms)=67
                CPU time spent (ms)=3290
                Physical memory (bytes) snapshot=410132480
                Virtual memory (bytes) snapshot=3195957248
                Total committed heap usage (bytes)=579862528
                Peak Map Physical memory (bytes)=206913536
                Peak Map Virtual memory (bytes)=1600569344
        org.apache.hadoop.examples.terasort.TeraGen$Counters
                CHECKSUM=68613941816777
        File Input Format Counters
                Bytes Read=0
        File Output Format Counters
                Bytes Written=3200000
5.71user 0.24system 0:16.67elapsed 35%CPU (0avgtext+0avgdata 186336maxresident)k
0inputs+968outputs (0major+32289minor)pagefaults 0swaps

**Comment by erikabreo16** [comment]
--time teragen

[root@ip-172-31-38-4 centos]# time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar teragen 1000000000 /benchmarks/teragen-100gb-test-3
17/07/19 21:03:33 INFO client.RMProxy: Connecting to ResourceManager at ip-172-31-43-140.us-west-2.compute.internal/172.31.43.140:8032
17/07/19 21:03:33 WARN security.UserGroupInformation: PriviledgedActionException as:root (auth:SIMPLE) cause:org.apache.hadoop.security.AccessControlException: Permission denied: user=root, access=EXECUTE, inode="/user":mapred:supergroup:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:279)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:260)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkTraverse(DefaultAuthorizationProvider.java:201)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:154)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:152)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:3529)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6650)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:4278)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:901)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getFileInfo(AuthorizationProviderProxyClientProtocol.java:528)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:839)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

org.apache.hadoop.security.AccessControlException: Permission denied: user=root, access=EXECUTE, inode="/user":mapred:supergroup:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:279)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:260)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkTraverse(DefaultAuthorizationProvider.java:201)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:154)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:152)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:3529)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6650)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:4278)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:901)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getFileInfo(AuthorizationProviderProxyClientProtocol.java:528)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:839)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2125)
        at org.apache.hadoop.hdfs.DistributedFileSystem$20.doCall(DistributedFileSystem.java:1253)
        at org.apache.hadoop.hdfs.DistributedFileSystem$20.doCall(DistributedFileSystem.java:1249)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1249)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1417)
        at org.apache.hadoop.mapreduce.JobSubmissionFiles.getStagingDir(JobSubmissionFiles.java:116)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:148)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1325)
        at org.apache.hadoop.examples.terasort.TeraGen.run(TeraGen.java:305)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.examples.terasort.TeraGen.main(TeraGen.java:309)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=root, access=EXECUTE, inode="/user":mapred:supergroup:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:279)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:260)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkTraverse(DefaultAuthorizationProvider.java:201)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:154)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:152)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:3529)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6650)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:4278)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:901)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getFileInfo(AuthorizationProviderProxyClientProtocol.java:528)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:839)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

        at org.apache.hadoop.ipc.Client.call(Client.java:1502)
        at org.apache.hadoop.ipc.Client.call(Client.java:1439)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at com.sun.proxy.$Proxy16.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
        at com.sun.proxy.$Proxy17.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2123)
        ... 30 more

real    0m2.741s
user    0m4.357s
sys     0m0.197s

**Comment by erikabreo16** [comment]
--salida terasort

[root@ip-172-31-38-4 hadoop-mapreduce]# sudo -u erikabreo16 time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar terasort /user/erikabreo16/teragen /user/erikabreo16/terasort
17/07/19 23:00:36 INFO terasort.TeraSort: starting
17/07/19 23:00:38 INFO input.FileInputFormat: Total input paths to process : 2
Spent 135ms computing base-splits.
Spent 2ms computing TeraScheduler splits.
Computing input splits took 137ms
Sampling 2 splits of 2
Making 8 from 32000 sampled records
Computing parititions took 507ms
Spent 647ms computing partitions.
17/07/19 23:00:38 INFO client.RMProxy: Connecting to ResourceManager at ip-172-31-43-140.us-west-2.compute.internal/172.31.43.140:8032
17/07/19 23:00:39 INFO mapreduce.JobSubmitter: number of splits:2
17/07/19 23:00:39 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1500493697580_0004
17/07/19 23:00:39 INFO impl.YarnClientImpl: Submitted application application_1500493697580_0004
17/07/19 23:00:39 INFO mapreduce.Job: The url to track the job: http://ip-172-31-43-140.us-west-2.compute.internal:8088/proxy/application_1500493697580_0004/
17/07/19 23:00:39 INFO mapreduce.Job: Running job: job_1500493697580_0004
17/07/19 23:00:46 INFO mapreduce.Job: Job job_1500493697580_0004 running in uber mode : false
17/07/19 23:00:46 INFO mapreduce.Job:  map 0% reduce 0%
17/07/19 23:00:52 INFO mapreduce.Job:  map 100% reduce 0%
17/07/19 23:00:58 INFO mapreduce.Job:  map 100% reduce 13%
17/07/19 23:00:59 INFO mapreduce.Job:  map 100% reduce 38%
17/07/19 23:01:03 INFO mapreduce.Job:  map 100% reduce 50%
17/07/19 23:01:04 INFO mapreduce.Job:  map 100% reduce 75%
17/07/19 23:01:08 INFO mapreduce.Job:  map 100% reduce 100%
17/07/19 23:01:08 INFO mapreduce.Job: Job job_1500493697580_0004 completed successfully
17/07/19 23:01:08 INFO mapreduce.Job: Counters: 54
        File System Counters
                FILE: Number of bytes read=1376753
                FILE: Number of bytes written=4043670
                FILE: Number of read operations=0
                FILE: Number of large read operations=0
                FILE: Number of write operations=0
                HDFS: Number of bytes read=3200312
                HDFS: Number of bytes written=3200000
                HDFS: Number of read operations=30
                HDFS: Number of large read operations=0
                HDFS: Number of write operations=16
        Job Counters
                Launched map tasks=2
                Launched reduce tasks=8
                Data-local map tasks=1
                Rack-local map tasks=1
                Total time spent by all maps in occupied slots (ms)=8085
                Total time spent by all reduces in occupied slots (ms)=30399
                Total time spent by all map tasks (ms)=8085
                Total time spent by all reduce tasks (ms)=30399
                Total vcore-milliseconds taken by all map tasks=8085
                Total vcore-milliseconds taken by all reduce tasks=30399
                Total megabyte-milliseconds taken by all map tasks=8279040
                Total megabyte-milliseconds taken by all reduce tasks=31128576
        Map-Reduce Framework
                Map input records=32000
                Map output records=32000
                Map output bytes=3264000
                Map output materialized bytes=1376165
                Input split bytes=312
                Combine input records=0
                Combine output records=0
                Reduce input groups=32000
                Reduce shuffle bytes=1376165
                Reduce input records=32000
                Reduce output records=32000
                Spilled Records=64000
                Shuffled Maps =16
                Failed Shuffles=0
                Merged Map outputs=16
                GC time elapsed (ms)=334
                CPU time spent (ms)=17710
                Physical memory (bytes) snapshot=2535780352
                Virtual memory (bytes) snapshot=15985405952
                Total committed heap usage (bytes)=3437232128
                Peak Map Physical memory (bytes)=472092672
                Peak Map Virtual memory (bytes)=1589784576
                Peak Reduce Physical memory (bytes)=202682368
                Peak Reduce Virtual memory (bytes)=1611558912
        Shuffle Errors
                BAD_ID=0
                CONNECTION=0
                IO_ERROR=0
                WRONG_LENGTH=0
                WRONG_MAP=0
                WRONG_REDUCE=0
        File Input Format Counters
                Bytes Read=3200000
        File Output Format Counters
                Bytes Written=3200000
17/07/19 23:01:08 INFO terasort.TeraSort: done
6.80user 0.26system 0:33.11elapsed 21%CPU (0avgtext+0avgdata 194872maxresident)k
0inputs+1008outputs (0major+34257minor)pagefaults 0swaps

**Comment by erikabreo16** [comment]
--time terasort


[root@ip-172-31-38-4 centos]# sudo -u erikabreo16 time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar terasort /user/erikabreo16/teragen /user/erikabreo16/terasort
17/07/19 21:05:03 INFO terasort.TeraSort: starting
17/07/19 21:05:04 ERROR terasort.TeraSort: Permission denied: user=erikabreo16, access=EXECUTE, inode="/user":mapred:supergroup:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:279)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.check(DefaultAuthorizationProvider.java:260)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkTraverse(DefaultAuthorizationProvider.java:201)
        at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkPermission(DefaultAuthorizationProvider.java:154)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:152)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:3529)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkPermission(FSNamesystem.java:6650)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:4278)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:901)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getFileInfo(AuthorizationProviderProxyClientProtocol.java:528)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:839)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

3.38user 0.17system 0:02.49elapsed 142%CPU (0avgtext+0avgdata 159536maxresident)k
0inputs+968outputs (0major+28520minor)pagefaults 0swaps
[root@ip-172-31-38-4 centos]# time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar terasort /benchmarks/teragen-100gb-test-3 /benchmarks/terasort
17/07/19 21:12:21 INFO terasort.TeraSort: starting
17/07/19 21:12:22 ERROR terasort.TeraSort: Input path does not exist: hdfs://ip-172-31-38-4.us-west-2.compute.internal:8020/benchmarks/teragen-100gb-test-3

real    0m2.493s
user    0m3.389s
sys     0m0.160s
